export const TEST="TEST";
export const GET_USER="GET_USER";
export const REGISTER_USER = "REGISTER_USER";
export const SET_ALERT= "SET_ALERT";
export const REMOVE_ALERT= "REMOVE_ALERT";
export const LOGIN_USER= "LOGIN_USER";
export const LOAD_USER= "LOAD_USER";
export const LOGIN_FAILURE="LOGIN_FAILURE";
export const REGISTER_FAILURE= "REGISTER_FAILURE";
export const AUTH_ERROR= "AUTH_ERROR";
export const LOGOUT="LOGOUT";

export const UPDATE_PROFILE = "UPDATE_PROFILE"
export const UPDATE_PROFILE_FAILURE = "UPDATE_PROFILE_FAILURE"

export const CREATING_WITHDRAWAL = "CREATING_WITHDRAWAL"
export const CREATED_WITHDRAWAL = "CREATED_WITHDRAWAL"
export const WITHDRAWAL_FAILURE = "WITHDRAWAL_FAILURE"
export const GET_WITHDRAWAL_REQ = "GET_WITHDRAWAL_REQ"

